languageCode = "en-us"
title = "Joseph Earl"
baseURL = "https://www.josephearl.co.uk/"
theme = "cactus-plus"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    name = "Joseph Earl"
    description = "Joseph Earl`s Website"
    bio = "Senior Consultant <a href='https://www.thoughtworks.com'>@ThoughtWorks</a>"
    twitter = "josephearl"
    enableRSS = false

    # Nav
    aboutLink = "http://about.me/josephearl"

    # Disqus commenting
    enableDisqus = false

    # Duoshuo commenting
    enableDuoshuo = false

    # GitHub issues
    enableGithubIssuesTips = false

    # Use description as title in single page, posts page and tags page.
    useDescriptionAsTitle = false

    # Baidu analytics
    enableBaiduAnalytics = false
