# Save changes to GitHub
backend:
  name: github
  repo: josephearl/website
  branch: master

# Use the Editorial workflow - https://github.com/netlify/netlify-cms/blob/master/docs/editorial_workflow.md
publish_mode: editorial_workflow

# Save image uploads to static/img
media_folder: "static/images"
public_folder: "/images"

# Collections
collections: # A list of collections the CMS should be able to edit
  # Used in routes, ie.: /admin/collections/:slug/edit
  - name: "post"
    # Used in the UI, ie.: "New Post"
    label: "Post"
    # The path to the folder where the documents are stored
    folder: "content/post"
    # Allow users to create new documents in this collection
    create: true
    # Filename template e.g. YYYY-MM-DD-title.md
    slug: "{{slug}}"
    # The fields each document in this collection have
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", optional: true}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
# Does not currently work, see https://github.com/netlify/netlify-cms/issues/248
#      - {label: "Tags", name: "tags", widget: "list"}
#      - {label: "Categories", name: "categories", widget: "list"}
